experiment_name: network_delay_preprocessing
fault_config:
  name: network-delay-preprocessing
  duration: 300s
  fault_type: NetworkFault.DELAY
  fault_specific_config:
    name: network-delay-preprocessing
    namespace: default
    duration: 300s
    target:
      namespace: default
      label_selectors:
        app: preprocessing
    delay:
      latency: 100ms
      correlation: "0.5"
      jitter: 50ms
ground_truth: "your_ground_truth_here"

anomaly_injection_period: 600s
list_of_generator:
  - XXX.XXX.XXX.XXX
  - XXX.XXX.XXX.XXX
  - XXX.XXX.XXX.XXX
ssh_username: aaltosea
workload:
  type: docker
  config:
    image: rdsea/object_detection_client:latest
    args:
      host: http://XXX.XXX.XXX.XXX
      user: "8"
      run-time: 1020s
      spawn-rate: "1"
elastic_controller_config:
  elastic_used:
    - name: "Horizontal Pod Autoscaler"
      type: infrastructure
      active: true
      # how_to_activate: "user_defined_function_to_activate"
      # how_to_deactivate: "user_defined_function_to_deactivate"
