experiment_name: resourcehog_memory_preprocessing
fault_config:
  name: resourcehog-memory-preprocessing
  duration: 300s
  fault_type: ResourceHog.MEMORY
  fault_specific_config:
    name: resourcehog-memory-preprocessing
    namespace: default
    duration: 300s
    target:
      namespace: default
      label_selectors:
        app: preprocessing
    stress_mem:
      workers: 1
      size: 150MB
ground_truth: "your_ground_truth_here"

anomaly_injection_period: 300s
list_of_generator:
  - XXX.XXX.XXX.XXX
  - XXX.XXX.XXX.XXX
  - XXX.XXX.XXX.XXX
ssh_username: aaltosea
workload:
  type: docker
  config:
    image: rdsea/object_detection_client:latest
    args:
      host: http://XXX.XXX.XXX.XXX
      user: "24"
      run-time: 1020s
      spawn-rate: "10"
elastic_controller_config:
  elastic_used:
    - name: "Horizontal Pod Autoscaler"
      type: infrastructure
      active: false
      # how_to_activate: "user_defined_function_to_activate"
      # how_to_deactivate: "user_defined_function_to_deactivate"
monitor_config:
  prometheus_url: http://XXX.XXX.XXX.XXX/prometheus
  # K8s
  # prometheus_url: http://prometheus-kube-prometheus-prometheus.redpanda.svc.cluster.local:9090/prometheus
  namespace: observe
  kubernetes_path: "~/.kube/config"
