experiment_name: resourcehog_cpu_preprocessing
number_of_run: 3
time_between_run: 60s
clean_up: false
fault_config:
  name: resourcehog-cpu-preprocessing
  duration: 60s
  fault_type: ResourceHog.CPU
  fault_specific_config:
    name: resourcehog-cpu-preprocessing
    namespace: default
    duration: 60s
    target:
      namespace: default
      label_selectors:
        app: preprocessing
    stress_cpu:
      workers: 1
      load: 100
ground_truth: "your_ground_truth_here"

anomaly_injection_period: 900s
list_of_generator:
  - XXX.XXX.XXX.XXX
  - XXX.XXX.XXX.XXX
  - XXX.XXX.XXX.XXX
ssh_username: aaltosea
workload:
  type: docker
  config:
    image: rdsea/object_detection_client:latest
    args:
      host: http://XXX.XXX.XXX.XXX
      user: "5"
      run-time: 970s
      spawn-rate: "5"
elastic_controller_config:
  elastic_used:
    - name: "Horizontal Pod Autoscaler"
      type: infrastructure
      active: false
      # how_to_activate: "user_defined_function_to_activate"
      # how_to_deactivate: "user_defined_function_to_deactivate"
monitor_config:
  metric_url: http://XXX.XXX.XXX.XXX/prometheus
  # K8s
  # prometheus_url: http://prometheus-kube-prometheus-prometheus.redpanda.svc.cluster.local:9090/prometheus
  namespace: observe
  kubernetes_path: "~/.kube/config"
