name: network-chaos
# namespace: chaos-testing
duration: 60s
bandwidth:
  buffer: null
  limit: 1000
  minburst: null
  peakrate: null
  rate: 500kbps
delay:
  correlation: "50"
  jitter: 20ms
  latency: 100ms
loss:
  correlation: null
  loss: "25"
target:
  label_selectors:
    app: my-app
  namespace: default
