experiment_name: resource_cpu_ensemble
number_of_run: 3
time_between_run: 60s
clean_up:
  activate: true
  observability_cleanup_script: "/u/49/anhdun1/unix/git/RCA_Edge_Cloud/benchmark/experiment_controller/docs/observability_cleanup_script.sh"
  application_cleanup_script: "/u/49/anhdun1/unix/git/RCA_Edge_Cloud/benchmark/experiment_controller/docs/application_cleanup_script.sh"
fault_config:
  name: resource-cpu-ensemble
  duration: 300s
  fault_type: ResourceHog.CPU
  fault_specific_config:
    name: resource-cpu-ensemble
    namespace: default
    duration: 300s
    target:
      namespace: default
      label_selectors:
        app: ensemble
    stress_cpu:
      workers: 1
      load: 100
ground_truth: "ensemble_service:cpu_usage"
anomaly_injection_period: 900s
warm_up_interval: 300s
list_of_generator:
  - edge-raspi3.cs.aalto.fi
  # - edge-raspi4.cs.aalto.fi
  # - edge-raspi5.cs.aalto.fi
ssh_username: aaltosea
workload:
  type: docker
  config:
    image: rdsea/object_detection_client:latest
    args:
      host: http://XXX.XXX.XXX.XXX
      user: "5"
      run-time: 1200s
      spawn-rate: "0.1"
# elastic_controller_config:
#   elastic_used:
#     - name: "Horizontal Pod Autoscaler"
#       type: infrastructure
#       active: false
#       how_to_activate: "user_defined_function_to_activate"
#       how_to_deactivate: "user_defined_function_to_deactivate"
monitor_config:
  metric_url: http://XXX.XXX.XXX.XXX/prometheus
  # K8s
  # prometheus_url: http://prometheus-kube-prometheus-prometheus.redpanda.svc.cluster.local:9090/prometheus
  namespace: observe
  kubernetes_path: "~/.kube/config"
