image:
  repository: scylladb
  pullPolicy: IfNotPresent
  tag: ""
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 32Mi
webhook:
  createSelfSignedCertificate: true
  certificateSecretName: "scylla-signed-certificate"
