apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  clusterSpec:
    external:
      domain: customredpandadomain.local
    auth:
      sasl:
        enabled: true
        mechanism: SCRAM-SHA-256
        users:
          - name: alice
            password: redpanda
    statefulset:
      podTemplate:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: DoesNotExist
      initContainers:
        setDataDirOwnership:
          enabled: true
    storage:
      persistentVolume:
        storageClass: "longhorn"
---
apiVersion: v1
kind: Secret
metadata:
  name: redpanda-alice-password
  namespace: redpanda
type: Opaque
stringData:
  password: "alicepassword"
