apiVersion: v1
kind: Pod
metadata:
  name: redpanda-client-pod
  labels:
    app: redpanda-client
  namespace: redpanda
spec:
  volumes:
    - name: tls-certs
      secret:
        secretName: redpanda-default-cert
  containers:
    - name: client-container
      image: curlimages/curl
      command: ["sleep", "3600"]
      volumeMounts:
        - name: tls-certs
          mountPath: /etc/tls/certs
          readOnly: true
