experiment_name: resource_memory_inference-mobilenetv2
number_of_run: 1
time_between_run: 60s
clean_up:
  activate: true
  observability_cleanup_script: "/u/49/anhdun1/unix/git/RCA_Edge_Cloud/benchmark/experiment_controller/docs/observability_cleanup_script.sh"
  application_cleanup_script: "/u/49/anhdun1/unix/git/RCA_Edge_Cloud/benchmark/experiment_controller/docs/application_cleanup_script.sh"
fault_config:
  name: resource-memory-inference-mobilenetv2
  duration: 300s
  fault_type: ResourceHog.MEMORY
  target:
    namespace: default
    environment:
      - edge
    label_selectors:
      app: inference-mobilenetv2
  fault_specific_config:
    namespace: default
    duration: 300s
    stress_memory:
      workers: 1
      size: 600MB
ground_truth: "inference-mobilenetv2_service:memory_usage"
anomaly_injection_period: 900s
warm_up_interval: 300s
workload:
  type: docker
  config:
    image: rdsea/object_detection_client:latest
    args:
      host: http://XXX.XXX.XXX.XXX
      user: "5"
      run-time: 1200s
      spawn-rate: "0.1"
  list_of_generator:
    - edge-raspi3.cs.aalto.fi
    # - edge-raspi4.cs.aalto.fi
    # - edge-raspi5.cs.aalto.fi
  ssh_username: aaltosea
# elastic_controller_config:
#   elastic_used:
#     - name: "Horizontal Pod Autoscaler"
#       type: infrastructure
#       active: false
#       how_to_activate: "user_defined_function_to_activate"
#       how_to_deactivate: "user_defined_function_to_deactivate"
data_collector_config:
  metric_url: http://XXX.XXX.XXX.XXX/prometheus
  trace_url: http://XXX.XXX.XXX.XXX/tempo
observability_cadence_config:
  metric_config:
    environment:
      - edge
      - cloud
    scrape_interval: 1s
    evaluation_interval: 1s
