experiment_name: network_loss_preprocessing
number_of_run: 3
time_between_run: 60s
clean_up:
  activate: false
fault_config:
  name: network-loss-preprocessing
  duration: 60s
  fault_type: NetworkFault.LOSS
  target:
    namespace: default
    environment:
      - edge
    label_selectors:
      app: preprocessing
  fault_specific_config:
    namespace: default
    duration: 60s
    loss:
      loss: "50"
      correlation: "0.5"
ground_truth: "your_ground_truth_here"

anomaly_injection_period: 600s
list_of_generator:
  - edge-raspi3.cs.aalto.fi
  # - edge-raspi4.cs.aalto.fi
  # - edge-raspi5.cs.aalto.fi
ssh_username: aaltosea
workload:
  type: docker
  config:
    image: rdsea/object_detection_client:latest
    args:
      host: http://XXX.XXX.XXX.XXX
      user: "5"
      run-time: 670s
      spawn-rate: "0.1"
# elastic_controller_config:
#   elastic_used:
#     - name: "Horizontal Pod Autoscaler"
#       type: infrastructure
#       active: false
#       how_to_activate: "user_defined_function_to_activate"
#       how_to_deactivate: "user_defined_function_to_deactivate"
data_collector_config:
  metric_url: http://XXX.XXX.XXX.XXX/prometheus
