image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest

mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: XXX.XXX.XXX.XXX:4317
        http:
          endpoint: XXX.XXX.XXX.XXX:4318

  # processors:
  # batch:

  exporters:
    prometheus:
      endpoint: "XXX.XXX.XXX.XXX:8889"
    otlp:
      endpoint: http://gateway.cloud-1.svc:5678

      tls:
        insecure: true

  connectors:
    spanmetrics:

  service:
    # extensions: [health_check, pprof, zpages]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [spanmetrics, otlp]

      metrics/spanmetrics:
        receivers: [spanmetrics]
        exporters: [prometheus]

ports:
  metrics:
    # The metrics port is disabled by default. However you need to enable the port
    # in order to use the ServiceMonitor (serviceMonitor.enabled) or PodMonitor (podMonitor.enabled).
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP
