image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest

mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: XXX.XXX.XXX.XXX:4317
        http:
          endpoint: XXX.XXX.XXX.XXX:4318

  # processors:
  #   batch:

  exporters:
    otlp:
      endpoint: http://tempo-distributor.observe:4317
      tls:
        insecure: true

  service:
    # extensions: [health_check, pprof, zpages]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]

ports:
  metrics:
    enabled: false
