anomaly_injection_period: 900s
clean_up:
  activate: true
  application_cleanup_script: /u/49/anhdun1/unix/git/RCA_Edge_Cloud/benchmark/experiment_controller/docs/application_cleanup_script.sh
  observability_cleanup_script: /u/49/anhdun1/unix/git/RCA_Edge_Cloud/benchmark/experiment_controller/docs/observability_cleanup_script.sh
experiment_name: network_delay_preprocessing
fault_config:
  duration: 300s
  fault_specific_config:
    bandwidth: null
    delay:
      correlation: '0.5'
      jitter: 20ms
      latency: 50ms
    duration: 300s
    loss: null
    name: network-delay-preprocessing
    namespace: default
    target:
      label_selectors:
        app: preprocessing
      namespace: default
  fault_type: NetworkFault.DELAY
  name: network-delay-preprocessing
ground_truth: preprocessing_service:rtt
list_of_generator:
- edge-raspi3.cs.aalto.fi
monitor_config:
  kubernetes_path: ~/.kube/config
  metric_url: http://XXX.XXX.XXX.XXX/prometheus
  namespace: observe
number_of_run: 3
ssh_username: aaltosea
time_between_run: 60s
warm_up_interval: 300s
workload:
  config:
    args:
      host: http://XXX.XXX.XXX.XXX
      run-time: 1200s
      spawn-rate: '0.1'
      user: '5'
    image: rdsea/object_detection_client:latest
  type: docker
